### ISSUE TITLE
fake

### ISSUE THREAD

**Issue by Stanley-GF** [dropout1337/This-Repo-Has-null-Stars#3]
dropout ur a liar. this repos has currently 52 stars. 
i hate liars.

**Comment by Stanley-GF** [comment]
52>>41
i will prove it
if you do
1) `52-41`, the result is positive.
2) If you create a boolean in any languages, result will be true.
3) If you divide 52/x=1, x = 52, 
    52 for 1
    41 for 0,788461538

     1 is clearly superior

4) If you reffer to [quantum logic](https://en.wikipedia.org/wiki/Quantum_logic) you can clarly affirm that in every situations, 52 will be always superior.
5) Using this scheme, you can clarly affirm that ur wrong
![image](https://user-images.githubusercontent.com/66573599/131898823-c305bc81-abeb-48e6-9132-dd93b1f6c3f1.png)

## You, Mr. Dropout is a liar.

**Comment by KappasDEV** [comment]
Stanley going all out on u dropout lol
